export * from "./DisplayQueue";
export * from "./DoctorList";
export * from "./NavBar";
export * from "./NewDoctorPanel";
export * from "./NewPatientPanel";
export * from "./OnDutyDoctors";
export * from "./QueuePanel";
export * from "./TicketList";
export * from "./UpdateDoctorModal";
